### PR TITLE
[WIP] Initial attempt at supporting default unit settings

### PR DESCRIPTION
**Pull request by kfdm**
This is a very, very rough draft of playing with the idea from #13 

This assumes a settings file like the following

```
{
  "auto_convert": {
    "degC": [
      "degF"
    ],
    "km": [
      "mi"
    ],
    "mi": [
      "km"
    ]
  }
}
```

I've kept the settings as a list for now, since that's what the original ticket talked about, but since this was just my first prototype, it only works with a single conversion. I would need to change additional logic to have something like km -> miles, meters (one unit showing the result for two different destinations)

I'm sure this pull request is nowhere near ready for anything, but I thought it would be good to put a bit of code out there to start the discussion. At a very minimum I would imagine that @deanishe will have a few preferences on naming conventions for variables and layout of the settings file :)

### CODE REVIEW

**Comment by kfdm** [comment]
Since I'm on Alfred 3 on my only machine, I'm not going to try to handle the UI side of things, but just the logic assuming that you can manually edit the settings.json. Can probably handle the UI logic in a separate pull request if things look good.

**Comment by deanishe** [comment]
Sorry I didn't reply sooner. I totally missed this PR.

A good start, but I think a better way is to specify default units for dimensions, not just other units. So rather than mapping, say kilometres to miles, you map length to kilometres and miles. Or currency to USD, EUR and GBP.

I think that might save a lot of duplication of effort for users.

**Comment by deanishe** [comment]
I've added a method that maps default units to dimensionality rather than other units.

**Comment by kfdm** [comment]
Thanks! Your implementation looks better. :)

**Pull request closed without merging**
